site_name: My CV
theme:
  name: material
  palette:
    primary: 'indigo'
    accent: 'pink'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features:
    - navigation.tabs
    - navigation.instant
nav:
  - Home: index.md
  - About: about.md
  - Experience: experience.md
  - Education: education.md
  - Skills: skills.md
  - Projects: projects.md
plugins:
  - search
  - redirects
  - exclude:
      glob:
        - "README.md"
        - "*.bak"
        - "*.old"
  - awesome-pages
  - glightbox
  - minify
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  - toc:
      permalink: true
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/gsap/3.7.1/gsap.min.js
extra_css:
  - assets/stylesheets/custom.css
extra_javascript:
  - assets/javascripts/animations.js

